routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('dologin');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/vote/{event?}', 'HomeController@vote')->name('vote');
Route::get('/thanks', 'HomeController@thanks')->name('thanks');
Route::resource('/scores', 'ScoreController',['only' => ['store','update'] ]);

Route::prefix('/admin')->middleware('admin')->group(function() {
	Route::get('/','AdminController@index');
	Route::post('update-event','AdminController@updateCurrentEvent')->name('set-current-event');
	Route::resource('/misses', 'MissController');
	Route::resource('/cities', 'CityController');
	Route::resource('/events', 'EventController');
	Route::resource('/users', 'UserController');
	//EMERGENCIAS!!
	//Route::get('reset','AdminController@reset')->name('reset');
	Route::post('reset','AdminController@reset')->name('reset');

	Route::get('print/{type}','PdfController@print')->name('print');
});

resources/views/app/home.blade.php
@extends('layouts.frontend')

@section('content')
<div class="container-index  ">
    <div class="vertical-center inner-container col-md-10 col-md-offset-1 ">
        <img src="{{ asset('images/logo_reinas.png') }}" style="width: 70%;display: block;margin:0 auto" class="img-responsive text-center" alt="">
        <h1 class="text-center"> {{config('app.name')}} - {{date('Y')}}  </h1>

        <div class="panel panel-default back-logo-institution">
            <div class="panel-heading text-center" style="font-size: 20px"><b>Seleccione un evento para continuar</b>
                <br>
                <a class="btn btn-danger" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();"> <i class="fa fa-sign-out"></i> Salir</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </div>

            <div class="panel-body">
                <div class="row">                    
                    <div class="col-md-4 col-md-offset-4 text-center">
                        <a href="@can('vote'){{ route('vote',['evento'=>$current_event->generateSlug()]) }}@endcan @cannot('vote')#@endcannot" title="" class="event-icon  @cannot('vote') disabled @endcannot">
                            @can('vote')
                                <img src="{{ asset($current_event->getImg()) }}" alt="">
                            @endcan
                            @cannot('vote')
                                <img src="{{ asset($current_event->getImg(true)) }}" alt="">
                            @endcannot
                            <span>{{$current_event->name}}</span>
                        </a>
                    </div>
{{-- 
                    @can('vote',$current_event)
                    <div class="col-md-4 text-center">
                        <a href="{{ route('vote',['evento'=>'vestido_noche']) }}" title="" class="event-icon">
                            <img src="{{ asset('images/vestido_noche.png') }}" alt="">
                            <span>Traje de Noche</span>
                        </a>
                    </div>
                    @endcan

                    @can('vote',$current_event)
                    <div class="col-md-4 text-center">
                        <a href="{{ route('vote',['evento'=>'vestido_traje_banio']) }}" title="" class="event-icon">
                            <img src="{{ asset('images/vestido_traje_banio.png') }}" alt="">
                            <span>Traje de Baño</span>
                        </a>
                    </div>
                    @endcan

                    @can('vote',$current_event)
                    <div class="col-md-4 text-center">
                        <a href="{{ route('vote',['evento'=>'ronda_preguntas']) }}" title="" class="event-icon">
                            <img src="{{ asset('images/ronda_preguntas.png') }}" alt="">
                            <span>Ronda de Preguntas</span>
                        </a>
                    </div>
                    @endcan

                    @can('vote',$current_event) 
                    <div class="col-md-4 text-center">
                        <a href="{{ route('vote',['evento'=>'ronda_preguntas']) }}" title="" class="event-icon">
                            <img src="{{ asset('images/ronda_preguntas.png') }}" alt="">
                            <span>Desempate</span>
                        </a>
                    </div>
                    @endcan --}} 
                </div>

                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/show.blade.php
@extends('layouts.frontend')

@section('content')
<div class="container-index">
    <div class="vertical-center inner-container col-md-10 col-md-offset-1 back-logo-institution">
    	{{-- <img src="{{ asset('images/logo_reinas.png') }}" style="width: 15%;display: block;margin:0 auto" class="img-responsive text-center" alt=""> --}}
        <h1 class="text-center"> {{config('app.name')}} {{date('Y')}} - {{$current_event->name}} </h1>
        <p class="text-center">
			Hola, {{Auth::user()->username}}
			<br>
	        <a class="btn btn-danger" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();"> <i class="fa fa-sign-out"></i> Salir</a>
	        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
	            {{ csrf_field() }}
	        </form>
        </p>

        @foreach ($misses as $miss)
	        <h3 class="text-center show-miss-header text-uppercase"><b>{{strtoupper($miss->city->name)}}</b></h3>
	        <div class="col-md-8">
	        	<img src="{{ asset($miss->photos) }}" alt="" class="img-responsive text-center img-block" style="width: 42%!important">
	        </div>
	        <div class="col-md-4">
	        	<div class="data-section">
	        		<h4 class="text-center"><b>Datos</b></h4>
		        	<ul class="list-unstyled">
		        		<li><b>Nombres:</b> {{$miss->name}} {{$miss->last_name}}</li>
		        		<li><b>Edad:</b> {{$miss->age}} Años</li>
		        		<li><b>Estatura:</b> {{$miss->height}}</li>
		        		<li><b>Medidas:</b> {{$miss->measurements}}</li>
		        		<li><b>Hobbies:</b> {{$miss->hobbies}}</li>
		        	</ul>
		        	@can('vote')
		        	<hr style="margin: 0px">
		        	<form action="@if(App\Score::getId($current_event->id,$miss->city->id,Auth::id())){{ route('scores.update',['id' => App\Score::getId($current_event->id,$miss->city->id,Auth::id())]) }} @else {{ route('scores.store') }} @endif" method="POST">
		        		{{ csrf_field() }}
		        		@if (App\Score::getId($current_event->id,$miss->city->id,Auth::id()))
		        			<input type="hidden" name="_method" value="PUT">
		        		@endif
		        		<h3 class="text-center"><b>Puntaje</b></h3>
		        		<input type="hidden" name="event_id" value="{{$current_event->id}}">
		        		<input type="hidden" name="user_id" value="{{Auth::id()}}">
		        		<input type="hidden" name="city_id" value="{{$miss->city->id}}">
		        		<input type="hidden" name="current_page" value="@if(Request::has('page')) {{Request::get('page')}}@else 1 @endif">
		        		<select name="value" class="form-control" id="puntaje">
		        			@for ($i = 1; $i <=10 ; $i++)
		        				<option value="{{$i}}" @if(App\Score::get($current_event->id,$miss->city->id,Auth::id()) == $i) selected @endif>{{$i}} Puntos</option>
		        			@endfor
		        		</select>
		        		<button type="submit" class="btn btn-vote btn-block btn-lg"><i class="fa fa-heart"></i> <b>VOTAR</b></button>
		        	</form>
		        	<hr style="margin-top: 5px">
		        	@endcan
		        	<a class="btn btn-primary btn-block" href="{{ url('/home') }}"><i class="fa fa-home"></i> IR A INICIO</a>
	        	</div>
	        </div>
        @endforeach
        <div class="col-md-12 text-center">
        	{{$misses->links()}}
        </div>
    </div>
</div>
@endsection()

resources/views/app/thanks.blade.php
@extends('layouts.frontend')
@section('content')
	<div class="container-index">
		<div class="vertical-center inner-container col-md-10 col-md-offset-1" style="margin-top: 4%">
			<img src="{{ asset('images/logo_reinas.png') }}" style="width: 40%!important;display: block;margin:0 auto" class="img-responsive text-center" alt="">
			<div class="row">
				<h1 class="text-center col-md-6 col-md-offset-3" style="font-size: 40px"> GRACIAS POR VOTAR POR {{strtoupper($current_event->name)}} </h1>
			</div>
			<div class="row">
				<a class="text-center btn btn-primary col-xs-4 btn-lg col-md-6 col-md-offset-3" href="{{ url('/home') }}" title="" class="">Volver</a>
			</div>
		</div>
	</div>
@endsection